backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/_content/blog'
    identifier_field: 'slug'
    create: true
    slug: '{{slug}}_{{lang}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
        required: true
        pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Lol']

      - label: 'Language'
        name: 'lang'
        widget: 'select'
        options:
          - { label: 'ru ğŸ‡·ğŸ‡º', value: 'ru' }
          - { label: 'en ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿', value: 'en' }
        default: 'ru'
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: 'Featured Image'
        name: 'thumbnail'
        widget: 'object'
        fields:
          - { label: 'Image', name: 'img', widget: 'image' }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'Source link', name: 'src', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Preface', name: 'preface', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
